replicaCount: 1

image:
  repository: s4e-kod-asistani-backend
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 8080
  nodePort: 31008


env:
  OLLAMA_URL: "http://ollama-service:11434/api/generate"

ollama:
  enabled: true
  image:
    repository: ollama/ollama
    tag: latest
  service:
    type: ClusterIP
    port: 11434
