{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: "{{ .Values.ollama.service.type }}"
  selector:
    app: "{{ .Release.Name }}-ollama"
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: {{ .Values.ollama.service.port }}
{{- end }}
